---
- name: Site Down
  hosts: all
  gather_facts: false
  become: true
  
  tasks:
    - debug:
        msg: "Website is down!"
    - name: ensure Apache is installed
      ansible.builtin.package:
        name: apache2
        state: present
        
    - name: install website documents
      ansible.builtin.copy:
       src: index.html
       dest: /var/www/html/
       owner: root
       group: root
       mode: '0644'
       
    - name: Restart Apache
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: true
      
